import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: {
    default: 'Next JS learning', // fallback if child route doesn't have any title
    template: '%s | My learning progress', // can be as prefix or suffice after the child route's title
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
          <Header />
          {/* Wrap the children in a div that grows to fill available space */}
          <div className="grow">
            {children}
          </div>
          <footer className="bg-gray-400 p-1 text-black">
            Footer
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
